
services:

  postgres_db:
    image: postgres
    restart: always
    ports:
      - 5432:5432/tcp
    environment: 
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - PGDATA=/var/lib/postgresql/data/pgdata
      - POSTGRES_DB=mydatabase
    volumes:
      - ./data:/var/lib/postgresql/data 
    networks:
      - db_network

  pgadmin:
    image: dpage/pgadmin4:latest
    restart: always
    ports:
      - 8001:8080/tcp
    environment: 
      - PGADMIN_LISTEN_ADDRESS=0.0.0.0
      - PGADMIN_LISTEN_PORT=8080
      - PGADMIN_DEFAULT_EMAIL=admin@example.com
      - PGADMIN_DEFAULT_PASSWORD=admin
    networks:
      - db_network
    # ADD THIS LINE, TO BE ABLE TO LOGIN
    tty: true
    depends_on: # <-- !!!!!
      - postgres_db # <-- !!!!!
    links: # <-- !!!!!
      - postgres_db # <-- !!!!!
  mariadb:
    image: mariadb:latest
    restart: always
    ports:
      - 3306:3306/tcp
    environment:
      - MYSQL_ROOT_PASSWORD=rootpassword
      - MYSQL_DATABASE=mydatabase
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
    volumes:
      - ./mariadb_data:/var/lib/mysql
    networks:
      - db_network
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    restart: always
    ports:
      - 8080:80/tcp
    environment:
      - PMA_HOST=mariadb
      - PMA_PORT=3306
      - PMA_USER=user
      - PMA_PASSWORD=password
    networks:
      - db_network
    depends_on:
      - mariadb
    links:
      - mariadb 

networks:
  db_network:
    driver: bridge